### ISSUE TITLE
Add Gitpod support

### ISSUE THREAD

**Issue by h-enk** [gethyas/create-hyas#5]
- [ ] Add `.gitpod.yml`:

```yml
# Source:
# - https://github.com/gitpod-io/template-hugo
# - https://www.gitpod.io/docs/configure/workspaces/tasks#one-line-tasks

tasks:
  - name: Run development server
    init: pnpm install
    command: pnpm dev

ports:
  - port: 1313
    onOpen: open-preview
```
